### ISSUE TITLE
How to stop repeating coverflow

### ISSUE THREAD

**Issue by skyshine999** [applm/ma-components#20]
i want to stop circular repeating

**Comment by applm** [comment]
It is not possible. You can use my other library CarouselWidget

**Comment by skyshine999** [comment]
in carouselwidget library also same issue

**Comment by applm** [comment]
Well. Than read javadoc. It worked for me.

**Comment by DanielOuwendijk** [comment]
notifyDataSetChanged(); stops coverflow from getting repeated
